version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: fullapp-nginx
    ports:
      - "3000:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - fast-api-app
      - frontend
    networks:
      - my-shared-network
  fast-api-app:
    image: localhost/my-python-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    networks:
      - my-shared-network
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - my-shared-network
  app-bot:
    image: localhost/my-python-app-bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - fast-api-app
    env_file:
      - ./bot/.env
    networks:
      - my-shared-network
  postgres:
    image: docker.io/postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-shared-network
    restart: always

volumes:
  postgres_data:

networks:
  my-shared-network:
    driver: bridge
